### ISSUE TITLE
hmm coś wybuchło, ale nie bomba, tylko Exception mnie na dzień dobry rozerwał

### ISSUE THREAD

**Issue by piaskowyk** [franczakr/minesweeper#1]
[info] Running Minesweeper
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:337)
        at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:307)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:880)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)

**Comment by franczakr** [comment]
Dziwne u mnie działa
